kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: socks-catalogue-db
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
